# Generated by Django 6.0.4 on 2026-04-27 09:31

import django.core.validators
import django.db.models.deletion
import scheduling.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(default=30, validators=[django.core.validators.MinValueValidator(1)])),
                ('availability_start_date', models.DateField(default=scheduling.utils.default_availability_start_date)),
                ('availability_end_date', models.DateField(default=scheduling.utils.default_availability_end_date)),
                ('timezone', models.CharField(default='UTC', max_length=64, validators=[scheduling.utils.validate_timezone])),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invitee_name', models.CharField(max_length=255)),
                ('invitee_email', models.EmailField(max_length=254)),
                ('note', models.TextField(blank=True)),
                ('invitee_timezone', models.CharField(max_length=64, validators=[scheduling.utils.validate_timezone])),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='scheduling.event')),
            ],
            options={
                'ordering': ['-starts_at'],
                'constraints': [models.UniqueConstraint(fields=('event', 'starts_at'), name='unique_event_booking_start')],
            },
        ),
        migrations.CreateModel(
            name='EventAvailabilityRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_rules', to='scheduling.event')),
            ],
            options={
                'ordering': ['event', 'weekday', 'start_time'],
                'constraints': [models.UniqueConstraint(fields=('event', 'weekday'), name='unique_event_weekday_availability')],
            },
        ),
    ]
