# Generated by Django 6.0.4 on 2026-04-27 18:01

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='invitee_timezone',
            field=timezone_field.fields.TimeZoneField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='timezone',
            field=timezone_field.fields.TimeZoneField(default='UTC'),
        ),
    ]
